// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace midterm.Migrations
{
    [DbContext(typeof(MidtermDbContext))]
    [Migration("20190303095013_c2")]
    partial class c2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("midterm.Models.Product", b =>
                {
                    b.Property<int>("product_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("product_name");

                    b.Property<double>("product_price");

                    b.Property<int>("product_qty");

                    b.Property<int>("supplier_id");

                    b.HasKey("product_id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("midterm.Models.Supplier", b =>
                {
                    b.Property<int>("supplier_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("supplier_address");

                    b.Property<string>("supplier_name");

                    b.HasKey("supplier_id");

                    b.ToTable("Suppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
